### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by dazza-codes** [ld4l-labs/ontology#1]
@rjyounes explained the `reference` vs. `target` folder distinction:

- Reference is the entire external vocabulary, for reference
- What's included in the target ontology will be the fragments we are adopting in ld4l

**Comment by dazza-codes** [comment]
Note that the focus or outcome of this project is the ld4l ontology, currently a work-in-progress in:
- https://github.com/ld4l-labs/ontology/blob/master/target-ontologies/ld4l-o.owl

**Comment by dazza-codes** [comment]
Note that the ontology review and commentary process is coordinated in ontology calls and google documents (or wiki docs).  It's not in branches or PRs on this repository.

**Comment by dazza-codes** [comment]
The README could link out to related documents or wiki-docs on ontology use cases, or incorporate the use case documents into this repository.

**Comment by rjyounes** [comment]
Added suggestions to issue #12, closing this issue.
