### ISSUE TITLE
Work with Javed to create documentation overview

### ISSUE THREAD

**Issue by rjyounes** [ld4l-labs/ontology#14]
Ask Javed to do this or run it myself.

**Comment by rjyounes** [comment]
Tool doesn't handle rdf:Property

**Comment by rjyounes** [comment]
Tool to be revised (if possible) to link to live documentation provided by ontology owners, rather than creating our own LODE doc.

**Comment by rjyounes** [comment]
Javed,

Here are the URLs for the documentation of the namespaces:

bibliotek-o:
Namespace: http://bibliotek-o/ontology
Doc URL fragment: http://bibliotek-o.org/ontology.html#
Sample term:
    Local name: AddresseeActivity
    URL: http://bibliotek-o.org/ontology.html#AddresseeActivity

Bibframe: 
Namespace: http://id.loc.gov/ontologies/bibframe/
Doc URL fragment: http://id.loc.gov/ontologies/bibframe.html#
Sample class: 
    Local name: AcquisitionSource
    URL: http://id.loc.gov/ontologies/bibframe.html#c_AcquisitionSource
Sample property: 
    Local name: assigner
    URL: http://id.loc.gov/ontologies/bibframe.html#p_assigner

cidoc-crm:
Namespace: http://www.cidoc-crm.org/cidoc-crm/
Sample term:
    Local name: P2_has_type
    Doc URL: http://www.cidoc-crm.org/Property/p2-has-type/version-6.0
(This is the only term we are using in this namespace so you don't have to worry about other URL patterns.)

dcelements:
Namespace: http://purl.org/dc/elements/1.1/
Doc URL fragment: http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=elements#
Sample term:
    Local name: format
    URL: http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=elements#format

dcterms:
Namespace: http://purl.org/dc/terms/
Doc URL fragment: http://dublincore.org/documents/dcmi-terms/#
Sample term:
    Local name: date
    URL: http://dublincore.org/documents/dcmi-terms/#terms-date

foaf:
Namespace: http://xmlns.com/foaf/0.1/
Doc URL fragment: http://xmlns.com/foaf/spec/#term_
Sample term:
    Local name: Agent
    URL: http://xmlns.com/foaf/spec/#term_Agent

lingvoj: Skip. I can't find any documentation and we are only using one term.

oa:
Namespace: http://www.w3.org/ns/oa#
Doc URL fragment: https://www.w3.org/TR/annotation-vocab/#
Sample term:
    Local name: Annotation
    URL: https://www.w3.org/TR/annotation-vocab/#annotation

prov:
Namespace: http://www.w3.org/ns/prov#
Doc URL fragment: https://www.w3.org/TR/2013/REC-prov-o-20130430/#
Sample term:
    Local name: Location
    URL: https://www.w3.org/TR/2013/REC-prov-o-20130430/#Location

rdau:
Namespace: http://rdaregistry.info/Elements/u/
Doc URL fragment: http://www.rdaregistry.info/Elements/u/#
Sample term:
    Local name: P60001
    URL: http://www.rdaregistry.info/Elements/u/#P60001

schema:
Namespace: http://schema.org/
Doc URL fragment: http://schema.org/
Sample term:
    Local name: Event
    URL: http://schema.org/Event

skos:
Namespace: http://www.w3.org/2004/02/skos/core/
Doc URL fragment: https://www.w3.org/2009/08/skos-reference/skos.html#
Sample term:
    Local name: Concept
    URL: https://www.w3.org/2009/08/skos-reference/skos.html#Concept

vivo: You can also skip this. I can't find the type of doc we're looking for. Nothing useful comes out of LODE because there's nothing but a label and a range.

When you have created the page, can you attach it here and I'll add it to the repository?

Thanks a lot, Javed! Let me know if you have any questions.

**Comment by mjaved495** [comment]
Rebecca,

1. I believe http://bibliotek-o/ontology is not in use yet. I still see "bibx" in ontology files.
2. I see multiple bibframe ontology files in target ontologies folder. Can we clean up that folder and keep only those files that are in use.
3. I have created a github repo "ontologydoc" under ld4l-labs.
4. ontology doc can be accessed at https://ld4l-labs.github.io/ontologydoc/
5. Bibframe links are in working condition now. I will add other links once ready.
6. Let me know if something is not correct.

Thanks

**Comment by zimeon** [comment]
@mjaved495 - I pulled the current `develop` branch so  http://bibliotek-o.org/ontology shows the current bibliotek-o from repo (your #1 above) 

It would be easy to put your https://ld4l-labs.github.io/ontologydoc/ into http://bibliotek-o.org/ontologydoc/  or some similar path -- do we want that or would we be happy for it to live where it is?

**Comment by mjaved495** [comment]
That is strange. file is there. But then why I did not get the pull request. 
It seems I have different repo with me where Steven, Rebecca and others are committing their changes.

**Comment by mjaved495** [comment]
Rebecca, 
let me know when ontology changes are done. I will pull the latest changes and update the pages. Thanks

**Comment by rjyounes** [comment]
The ontology is final.

**Comment by mjaved495** [comment]
Alright. I will start my work then.

**Comment by mjaved495** [comment]
@zimeon Simeon, Can you please read the main paragraph (before image) on 
https://ld4l-labs.github.io/ontologydoc/ and let me know if you want to change anything there.

**Comment by sfolsom** [comment]
Javed,

FYI, I’ve updated the ontology diagram to reflect the decided namespace. It’s in the ontology diagram folder: https://drive.google.com/open?id=0B_emVObBVZQ1dlRCUEVEd3hIX3M

Thanks,
Steven

————
Steven Folsom
Metadata Technologies Program Manager
Harvard Library
http://orcid.org/0000-0003-3427-5769

**Comment by mjaved495** [comment]
I will update it today.
Thanks Steven.

Javed

**Comment by rjyounes** [comment]
The text needs to be updated - it is left over from the old ontology. @sfolsom should we just grab the text from the owl file and/or relevant parts of the readme? Do you want me to do this or do you want to do it?

**Comment by mjaved495** [comment]
Steven,

Can you please send the png or jpeg file or share the folder if you already have image file there?
My VUE software wants me to install legacy Java SE 6 :)

Thanks
Javed

**Comment by sfolsom** [comment]
I’ve been meaning to, but I haven’t been able to get to it. If you have ideas, feel free. Otherwise, I’ll get to it this afternoon.


————
Steven Folsom
Metadata Technologies Program Manager
Harvard Library
http://orcid.org/0000-0003-3427-5769

**Comment by rjyounes** [comment]
Since Steven is in the car I'll create the png and upload to the drive. I'll also work on the introductory text.

**Comment by sfolsom** [comment]
Done, already. ☺

————
Steven Folsom
Metadata Technologies Program Manager
Harvard Library
http://orcid.org/0000-0003-3427-5769

**Comment by rjyounes** [comment]
I've added the vue and png files to the repo under doc/overview. That's where I'll also put Javed's file. @sfolsom Do you want to include the vue file in the repo or just the png?

**Comment by rjyounes** [comment]
Never mind, the vue file should be included for editing purposes.

**Comment by sfolsom** [comment]
The PNG is probably most important.

If we think we want versioning and/or collaborative editing of the VUE file, we should keep the latest version of the file in the repo. I know for sure that I don't want to be seen as the sole owner of the diagram; contributions are welcomed. :)

Please forgive typos, sent from a mobile device.

On Apr 20, 2017, at 10:37 AM, Rebecca Younes <notifications@github.com<mailto:notifications@github.com>> wrote:


I've added the vue and png files to the repo under doc/overview. That's where I'll also put Javed's file. @sfolsom<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sfolsom&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=nOBG2_NbYDeeutfI6oVjC2-VeKxHfRfFN_eDQftfT6k&m=hrmfgfqVuOHJjauQTmtl4BPQugv5uBOh4YvojvnyW-g&s=uNA-JavQ-fsRPHqCu1hYRMedr6WpSWdGeeZ-r2wj9NE&e=> Do you want to include the vue file in the repo or just the png?

**Comment by rjyounes** [comment]
@mjaved495 Here's a stab at the text to be used with the diagram, adapted from the README.  @sfolsom @jak473 please edit as you wish. 

---------------------------------

bibliotek-o is an ontology recommendation for modeling bibliographic metadata. It includes:

* The bibliotek-o extension ontology, which defines additions and modifications to BIBFRAME 2, and is intended to be used as a supplement to the core BIBFRAME 2 ontology.
* A set of ontology fragments (including BIBFRAME 2) intended for use with the bibliotek-o extension.
* A set of models and patterns - i.e., an application profile - documenting the intended use of the preceding.

A high-level schematic representation of the bibliotek-o recommendation is shown below.

**Comment by mjaved495** [comment]
DONE. (from my point of view). Few tweaks are required that needs some troubleshooting. I think we are good for the meeting next week.  https://ld4l-labs.github.io/ontologydoc

**Comment by rjyounes** [comment]
Completed.
