### ISSUE TITLE
Work  with Alan and Chris to purchase domain and configure server

### ISSUE THREAD

**Issue by rjyounes** [ld4l-labs/ontology#15]
Purchase domain http://bibx.org. 
See [DLITSYS-2369](https://issues.library.cornell.edu/browse/DLITSYS-2369)

Set up/Configure server. See [DLITSYS-2371](https://issues.library.cornell.edu/browse/DLITSYS-2371):
- Need write access to copy ontology files and documentation.
- URLs: http://bibx.org/ontology.html, http://bibx.org/ontology.rdf
- What about other LODE docs and Javed's file?
- Redirect versionIRI to http://bibx.org/ontology/

**Comment by rjyounes** [comment]
Simeon is handling this.

**Comment by zimeon** [comment]
https://issues.library.cornell.edu/browse/DLITSYS-2369
