### ISSUE TITLE
Announcement of release 1.0

### ISSUE THREAD

**Issue by rjyounes** [ld4l-labs/ontology#18]
Links to ontology from wiki, etc.
Internal and/or public announcement.

**Comment by rjyounes** [comment]
Public announcement must be done sometime soon but perhaps not critical for the April 22 milestone.

**Comment by rjyounes** [comment]
Can be done in coordination with Michelle, but she doesn't have a github username.

**Comment by jak473** [comment]
@rjyounes : are we waiting to post the ontology to biblioteko/-o.org before announcing OR are we linking to the github repo? I was assuming the former but if that definitely won't be up and running for next week, I can send the announcement to various places once we decide on the hyphen issue... since I'll also share the pattern docs.

**Comment by jak473** [comment]
@rjyounes : just spoke with Michelle. She thinks we should wait until after the community & partner meetings to make a public announcement as communication strategy is on the agenda -- so this will inform. Plus we won't have much opportunity to engage next week if/when comments come in.

**Comment by rjyounes** [comment]
@jak473  Sounds fine to me. I was just going to ask you about date on the ontology. Currently I've set it for 4/21 at midnight, so that means it will predate the announcement. I think that's okay; would you agree?

**Comment by rjyounes** [comment]
@jak473 Does this mean we will not put links to ontology up on ld4l.org before the meeting?

**Comment by jak473** [comment]
@rjyounes : I don't think that is an issue; I just mean that we won't post its existence on listservs, etc., until we have a strategy. Cross-linking between wikis and websites we own works just fine (to me at least)
