### ISSUE TITLE
Review ontology includes and versioning practices

### ISSUE THREAD

**Issue by dazza-codes** [ld4l-labs/ontology#2]
@darrenleeweber:  So I understand that the `target` ontologies will be pruned for the LD4L-O and, at some point, copied into or collapsed into the LD4L-O?  (Trying to wrap my head around the implications, esp. for change management.)

@rjyounes:
- I would like to keep each namespace in a separate file. Right, there will not be a full import of the external ontos.
- I think using the fragment files is actually a good idea to shield ourselves from the ontology changes, until we have analyzed them to see if we want to update. Assuming of course that the ontology deprecates terms rather than removing them outright.
- This is an important issue to raise, we should think about it in more detail.

**Comment by dazza-codes** [comment]
Related W3C OWL documents that are relevant:
- https://www.w3.org/2007/OWL/wiki/Ontology_Versions
- https://www.w3.org/TR/owl2-syntax/#Ontology_IRI_and_Version_IRI
- https://www.w3.org/TR/owl2-syntax/#Versioning_of_OWL_2_Ontologies

Relevant slide presentation:
- http://www.slideshare.net/badenhughes/change-management-and-versioning-in-ontologies

**Comment by darrenleeweber** [comment]
Interesting survey:
http://www.mkbergman.com/906/a-brief-survey-of-ontology-development-methodologies/

**Comment by dazza-codes** [comment]
There are some tools for doing ontology diffs, e.g.
- http://www.ebi.ac.uk/efo/bubastis/
