### ISSUE TITLE
https://ld4l-labs.github.io/ - 404

### ISSUE THREAD

**Issue by dazza-codes** [ld4l-labs/ontology#27]
The 'Home' page hits a 404, see top left link from

https://ld4l-labs.github.io/ontologydoc/

**Comment by zimeon** [comment]
We should turn off the github.io site now we publish at http://bibliotek-o.org/overview.html

**Comment by zimeon** [comment]
https://ld4l-labs.github.io/ontologydoc/ is 404 also now. Done
