### ISSUE TITLE
Include reference geographic ontologies

### ISSUE THREAD

**Issue by dazza-codes** [ld4l-labs/ontology#3]
There may be existing geo-ontologies to include in the reference collection.

**Comment by dazza-codes** [comment]
Related to work at Harvard, noted in
- https://docs.google.com/presentation/d/1-lenZT8Z8lM-eRIpjkTg1aa_lUE5pyAatQAYzez_dpo/edit?usp=sharing
- https://wiki.harvard.edu/confluence/display/LibraryStaffDoc/Harvard+LD4L+Labs+Wiki

**Comment by rjyounes** [comment]
This might go into LD4P repositories. Needs discussion.

**Comment by dazza-codes** [comment]
See also work done in a prior NSF scientific grant:
- Proceedings from https://www.fgdc.gov/fgdc-news/spatial-ontology-cop-workshop
- https://www.nsf.gov/awardsearch/showAward?AWD_ID=0955816
- Nancy Wiegand wiegand@cs.wisc.edu was the PI

**Comment by rjyounes** [comment]
These will go into the cartographic extension.
