### ISSUE TITLE
Add tool to automatically normalize whitespace when committing an ontology file

### ISSUE THREAD

**Issue by rjyounes** [ld4l-labs/ontology#39]
It is hard to find actual changes in PRs with numerous whitespace modifications (see for example PR #36), and these changes are generally unnecessary.

@darrenleeweber mentions vim-mode as a possibility.

**Comment by zimeon** [comment]
Have you looked with `diff -b`? Though consistent formatting is probably a better solution

**Comment by rjyounes** [comment]
Duplicates #47.
