### ISSUE TITLE
Include moving-image ontology materials

### ISSUE THREAD

**Issue by dazza-codes** [ld4l-labs/ontology#4]
Related to work at Harvard, noted in:
- https://docs.google.com/presentation/d/1-lenZT8Z8lM-eRIpjkTg1aa_lUE5pyAatQAYzez_dpo/edit?usp=sharing
- https://wiki.harvard.edu/confluence/display/LibraryStaffDoc/Harvard+LD4L+Labs+Wiki

**Comment by rjyounes** [comment]
This might go into LD4P repositories. Needs discussion.

**Comment by rjyounes** [comment]
These will go into the MovingImage extension.
