### ISSUE TITLE
CHANGE definition of Class bib:ConservatorActivity

### ISSUE THREAD

**Issue by amberbilley** [ld4l-labs/ontology#43]
PR #36
bibliotek-o change request by the ArtFrame Community for 2017 Q2.

bib:ConservatorActivity
Label: Conservator
IRI: http://bibliotek-o.org/ontology/ConservatorActivity
Definition: The activity of documenting, preserving, or treating printed or manuscript material, works of art, artifacts, or other media.
 
Change definition to: The activity of preserving or treating printed or manuscript material, works of art, artifacts, or other objects.

**Comment by sfolsom** [comment]
I don't see a problem with the proposed change. 

Just a side note that most of the activity definitions come from wording found on MARC relators, and we've identified future work to include looking at formal relationships between bibliotek-o Activities and MARC relators. We'll have to make sure to remember these types of changes when we schedule the alignment work, in case it changes the decisions we might make.

**Comment by rjyounes** [comment]
@sfolsom The removal of "documenting" was a result of the ArtFrame and RareMat groups identifying a new Activity, ConditionAssessmentActivity, which includes the documentation of condition, whereas the ConservatorActivity involves the actual preservation or treatment. I don't think the extension groups have decided yet whether to request the activity be added to bibliotek-o or define in an extension.
