### ISSUE TITLE
Review and document ontology development practices

### ISSUE THREAD

**Issue by dazza-codes** [ld4l-labs/ontology#5]
The goal of this issue is to document development practices to help collaborators understand how to contribute.

Software engineering practices are well established for management of development vs. releases, they just need to be applied to ontology development.  One possibility is to use github (e.g. this repository), as it’s the primary platform for open-source projects.  However, it assumes those who work on ontology development have an understanding of working with git (or any code versioning system) or are willing to learn it or find ways to use the github-UI to get their work done.  The use of github is one option.  Another option is the protege-web platform, which is more specific to ontology development.  There may be other options.  It should be noted that both github and protege-web have privacy management tools available.  In any case, there is an argument for application of well established software engineering practices to the ontology development process.

The concern above is related to the actual implementation and document management details, rather than the broader design and consensus process.  W3C process could be considered/adapted to ontology collaborations, esp. the way they manage proposals vs. recommendation status?  Also wondering how schema.org manage things.

Some relevant OWL documents on versioning:
- https://www.w3.org/2007/OWL/wiki/Ontology_Versions
- https://www.w3.org/TR/owl2-syntax/#Ontology_IRI_and_Version_IRI
- https://www.w3.org/TR/owl2-syntax/#Versioning_of_OWL_2_Ontologies

Relevant slide presentation on change management:
- http://www.slideshare.net/badenhughes/change-management-and-versioning-in-ontologies

Interesting survey of systems for ontology development/collaboration:
- http://www.mkbergman.com/906/a-brief-survey-of-ontology-development-methodologies/

Also, Tania Tudorache is the lead developer of Protege at Stanford.  She could be invited to comment on the Protege community approach to ontology development, management, versioning etc.  From Stanford Who, her public contact details are:
- Email:  tudorache@stanford.edu 
- Web page: http://web.stanford.edu/~ttania/

**Comment by rjyounes** [comment]
Closing: not related to the ontology per se.
