### ISSUE TITLE
bf:relatedTo

### ISSUE THREAD

**Issue by melanieWacker** [ld4l-labs/ontology#57]
According to the [bibliotek-o relations patters document](https://wiki.duraspace.org/download/attachments/79795231/bibliotek-o_pattern_relations_201612.pdf?version=1&modificationDate=1492566953238&api=v2) we should be using bf:relatedTo, but I do not see that in our bf target ontology file. Should that be added?

**Comment by eslao** [comment]
I believe so. This was probably a goof on my part.

**Comment by rjyounes** [comment]
I can add it now, since I'm just about to release a new version to fix some doc updates.

**Comment by rjyounes** [comment]
Added term to bibframe target file.
